apiVersion: v1
kind: ConfigMap
metadata:
  name: symfony-k8s-nginx-config
  namespace: symfony-k8s
data:
  nginx-conf : |
    events {
    }
    http {
      server {
        listen 80;
            server_name  _;
        client_max_body_size 25M;
    
        root /var/www/symfony-k8s-app/public;
    
        location / {
            try_files $uri /index.php$is_args$args;
        }
    
        location ~ ^/(index|config|test)\.php(/|$) {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $realpath_root;
            add_header X-Frame-Options DENY always;
            add_header X-XSS-Protection "1; mode=block" always;
            add_header X-Content-Type-Options nosniff always;
            add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js https://cdn.jsdelivr.net/momentjs/latest/moment.min.js; style-src 'unsafe-inline' 'self'; img-src 'self' data:; frame-ancestors 'none'; form-action 'self';" always;
            add_header Referrer-Policy same-origin always;
            add_header Cross-Origin-Resource-Policy same-site always;
            add_header Cross-Origin-Opener-Policy same-origin always;
            add_header Cross-Origin-Embedder-Policy require-corp always;
        }
    
        error_log stderr;
        access_log /dev/stdout;
      } 
    }
